---
version: "3"
services:
  # Generic services

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.2.1
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - "9101:9101"
      - "9092:9092"
      - "3501:3501"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: LISTENER_BOB://broker:29092,LISTENER_FRED://broker:9092,LISTENER_ALICE://broker:3501
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://broker:29092,LISTENER_FRED://localhost:9092,LISTENER_ALICE://134.221.20.203:3501
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT,LISTENER_ALICE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=broker -Dcom.sun.management.jmxremote.rmi.port=9101

  schema_registry:
    image: confluentinc/cp-schema-registry:7.2.1
    hostname: schema_registry
    depends_on:
      - broker
    ports:
      - "3502:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  # Debugging tools

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 3600:8080
    depends_on:
      - zookeeper
      - broker
      - schema_registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9101
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema_registry:8081

  # Scenario Management

  # trial_management_tool:
  #   image: strategyeu/trial-management-tool:naas
  #   # image: strategyeu/trial-management-tool:test_image
  #   depends_on:
  #     - broker
  #     - schema_registry
  #   links:
  #     - broker
  #     - schema_registry
  #   ports:
  #     - "3210:3210"
  #   environment:
  #     CLIENT_ID: TB-TrialMgmt
  #     KAFKA_HOST: broker:29092
  #     SCHEMA_REGISTRY: schema_registry:8081
  #     TRIAL_MANAGER_SERVER_PORT: 3210
  #     SERVER: "http://localhost/tmt"
  #     PRODUCE: xvr_simulation_request_startinject,xvr_simulation_entity_post,xvr_simulation_request_move,xvr_simulation_request_route,send_file,send_message
  #   volumes:
  #     - trial-data:/app/trials

  # Configuring the environment

  bootstrapper:
    image: drivereu/silent-producer:latest
    hostname: bootstrapper
    depends_on:
      - broker
      - schema_registry
    environment:
      SLEEP: 20000 # Wait before registering schemas
      KAFKA_HOST: broker:29092
      SCHEMA_REGISTRY: schema_registry:8081
      PARTITION_SPECIFICATION: system_heartbeat:1:360000
    restart: on-failure
    volumes:
      - ./schemas:/app/src/schemas

volumes:
  trial-data:
