---
version: "3"
services:
  # Generic services

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - "3500:3500"
    environment:
      ZOOKEEPER_CLIENT_PORT: 3500
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    links:
      - zookeeper
    ports:
      - "3501:3501"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:3500"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:3501,PLAINTEXT://broker:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LISTENERS: "EXTERNAL://0.0.0.0:3501,PLAINTEXT://0.0.0.0:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 100000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 100000000
    restart: on-failure

  schema_registry:
    hostname: schema_registry
    image: ghcr.io/aiven/karapace:develop
    entrypoint:
      - /bin/bash
      - /opt/karapace/start.sh
      - registry
    depends_on:
      - broker
    ports:
      - "3502:8081"
    environment:
      KARAPACE_ADVERTISED_HOSTNAME: schema_registry
      KARAPACE_BOOTSTRAP_URI: broker:9092
      KARAPACE_PORT: 8081
      KARAPACE_HOST: 0.0.0.0
      KARAPACE_CLIENT_ID: karapace
      KARAPACE_GROUP_ID: schema_registry
      KARAPACE_MASTER_ELIGIBILITY: "true"
      KARAPACE_TOPIC_NAME: _schemas
      KARAPACE_LOG_LEVEL: WARNING
      KARAPACE_COMPATIBILITY: FULL
    restart: on-failure

  kafka_rest:
    hostname: kafka_rest
    image: ghcr.io/aiven/karapace:develop
    entrypoint:
      - /bin/bash
      - /opt/karapace/start.sh
      - rest
    depends_on:
      - broker
      - schema_registry
    ports:
      - "8085:8082"
    environment:
      KARAPACE_PORT: 8082
      KARAPACE_HOST: 0.0.0.0
      KARAPACE_ADVERTISED_HOSTNAME: kafka_rest
      KARAPACE_BOOTSTRAP_URI: broker:9092
      KARAPACE_REGISTRY_HOST: schema_registry
      KARAPACE_REGISTRY_PORT: 8081
      KARAPACE_ADMIN_METADATA_MAX_AGE: 0
      KARAPACE_LOG_LEVEL: WARNING
    restart: on-failure

  # Debugging tools

  kafka_schema_registry_ui:
    image: landoop/schema-registry-ui:latest
    hostname: kafka_schema_registry_ui
    links:
      - schema_registry
    ports:
      - "3601:8000"
    environment:
      SCHEMAREGISTRY_URL: schema_registry:8081
      PROXY: "true"
      MAX_BYTES: 10485760

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    hostname: kafdrop
    depends_on:
      - broker
      - schema_registry
    ports:
      - 3600:9000
    environment:
      KAFKA_BROKERCONNECT: broker:9092
      SCHEMAREGISTRY_CONNECT: http://schema_registry:8081
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
      SERVER_SERVLET_CONTEXTPATH: /
      CMD_ARGS: "--message.format=AVRO"

  # Scenario Management

  trial_management_tool:
    image: strategyeu/trial-management-tool:test_image
    depends_on:
      - broker
      - schema_registry
    links:
      - broker
      - schema_registry
    ports:
      - "3210:3210"
    environment:
      CLIENT_ID: TB-TrialMgmt
      KAFKA_HOST: broker:9092
      SCHEMA_REGISTRY: schema_registry:8081
      TRIAL_MANAGER_SERVER_PORT: 3210
      SERVER: "http://localhost/tmt"
      PRODUCE: xvr_simulation_request_startinject,xvr_simulation_entity_post,xvr_simulation_request_move,xvr_simulation_request_route
    volumes:
      - trial-data:/app/trials

  # Configuring the environment

  bootstrapper:
    image: drivereu/silent-producer:latest
    hostname: bootstrapper
    depends_on:
      - broker
      - schema_registry
    environment:
      KAFKA_HOST: broker:9092
      SCHEMA_REGISTRY: schema_registry:8081
    restart: on-failure
    volumes:
      - ./schemas:/app/src/schemas

volumes:
  trial-data:
